### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by IsaacSSilva** [Gui-HR/sky-ski#1]
### **O menu poderia ser usada como listas**

>Quero dizer.. 

Em caso do bot de leitura e análise do Google intensificar que são links que tem relação em comum, ele vai listra como algo em comum e não entender que são só links a esmo

#### **ele está assim**
![Screenshot_20230330-224344~2](https://user-images.githubusercontent.com/85599926/229004173-2364444a-61d8-42cc-bb6d-7f4368613a04.png)

#### **mas com a atualização poderia ser assim:**

```html

<header>
  <nav>
    <ul>
      <li> <a href="#">Sobre</a> </li>
      <li> <a href="#">Loja</a> </li>
      <li> <a href="#">Contato</a> </li>
    <\ul>
  </nav>
</header>

```

> Isso deixaria de forma mais padronizado com o seu front-end
> Mas lembre que isso não é regra é sim um regime de padrões 

Pensa com carinho 
**O que acha ?**
@Gui-HR

**Comment by Gui-HR** [comment]
Muito obrigado pela sujestão! Vou melhorar meu código
